name: Continuos Testing

on: 
  push:
    branches: 
      - 'feature/**'
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository contents
      uses: actions/checkout@v1

    - name: Latex-multicompiler
      uses: Jatus93/Latex-multicompiler@0.0.5a
