name: Continuous Testing

on:
  pull_request:
    branches:
      - develop
      - master
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository contents
      uses: actions/checkout@v1

    - name: Latex compiler
      uses: Jatus93/Latex-multicompiler@0.0.5a
      with:
        arg: -r

    - name: Actifact uplad
      uses: actions/upload-artifact@v1
      with:
        name: Documents.tar.gz
        path: ./
